spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cdtblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
logging:
  level:
    com.cdt.blog.dao: trace

setting:
  path: _cdtlog/cdtlog.setting
