server:
  port: 9001
  servlet:
    context-path: /api/v1
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  profiles:
    active: dev
logging:
  file:
    name: log/cdtblog.log
    path: log/
mybatis-plus:
  configuration:
    aggressive-lazy-loading: true